resolver: lts-14.6
packages:
- mix
- mix-json-logger
- mix-plugin-github
- mix-plugin-drone
- mix-plugin-shell
extra-deps:
- extensible-0.6.1
- membership-0
- github-0.22
- binary-instances-1
- drone-1.0.1
