resolver: lts-19.0
packages:
- mix
- helper/rio-logger-ext
- mix-json-logger
- mix-plugin-github
- mix-plugin-drone
- mix-plugin-shell
- mix-plugin-persistent-sqlite
- mix-plugin-xdgcache
extra-deps:
- extensible-0.8.3
- membership-0.0.1
- incremental-0.3.1
- github-0.27
- binary-instances-1.0.2
- drone-1.1.0
