resolver: lts-13.13
packages:
- mix
- mix-json-logger
- mix-plugin-github
- mix-plugin-drone
- mix-plugin-shell
- shh-cmd
extra-deps:
- extensible-0.5
- github-0.21
- shh-0.3.1.3
- github: matsubara0507/drone-haskell
  commit: aa6f5152dd9ea72cb48a32bdc58c91de2bdc21a9
