defaults:
  local: ../mix-base.yaml

name:                mix-plugin-github
version:             0.3.0
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2019 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- mix
- aeson
- github >= 0.24
- req >= 2.0

library:
  source-dirs: src
