defaults:
  local: ../mix-base.yaml

name:                mix-plugin-github
version:             0.1.1
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2019 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- mix
- github

library:
  source-dirs: src
